all_features = [
    'hour', 'day_of_week', 'week_of_year', 'year', '1_hours_ago_input_flow_rate_first', '1_hours_agot_input_flow_rate_last', 
    '1_hours_ago_input_flow_rate_mean', '1_hours_ago_reservoir_level_percentage_first', '1_hours_ago_reservoir_level_percentage_last', 
    '1_hours_ago_reservoir_level_percentage_mean', '1_hours_ago_output_flow_rate_first', '1_hours_ago_output_flow_rate_last', 
    '1_hours_ago_output_flow_rate_mean', '1_hours_ago_pressure_first', '1_hours_ago_pressure_last', '1_hours_ago_pressure_mean', 
    '1_hours_agot_pump_1_duration_sum', '1_hours_agot_pump_2_duration_sum', '1_hours_ago_temperature', '1_hours_ago_precipitation', 
    '1_hours_ago_humidity', '2_hours_ago_input_flow_rate_first', '2_hours_agot_input_flow_rate_last', '2_hours_ago_input_flow_rate_mean', 
    '2_hours_ago_reservoir_level_percentage_first', '2_hours_ago_reservoir_level_percentage_last', '2_hours_ago_reservoir_level_percentage_mean', 
    '2_hours_ago_output_flow_rate_first', '2_hours_ago_output_flow_rate_last', '2_hours_ago_output_flow_rate_mean', '2_hours_ago_pressure_first', 
    '2_hours_ago_pressure_last', '2_hours_ago_pressure_mean', '2_hours_agot_pump_1_duration_sum', '2_hours_agot_pump_2_duration_sum', '2_hours_ago_temperature', 
    '2_hours_ago_precipitation', '2_hours_ago_humidity', '3_hours_ago_input_flow_rate_first', '3_hours_agot_input_flow_rate_last', '3_hours_ago_input_flow_rate_mean', 
    '3_hours_ago_reservoir_level_percentage_first', '3_hours_ago_reservoir_level_percentage_last', '3_hours_ago_reservoir_level_percentage_mean', 
    '3_hours_ago_output_flow_rate_first', '3_hours_ago_output_flow_rate_last', '3_hours_ago_output_flow_rate_mean', '3_hours_ago_pressure_first', 
    '3_hours_ago_pressure_last', '3_hours_ago_pressure_mean', '3_hours_agot_pump_1_duration_sum', '3_hours_agot_pump_2_duration_sum', '3_hours_ago_temperature', 
    '3_hours_ago_precipitation', '3_hours_ago_humidity', '6_hours_ago_input_flow_rate_first', '6_hours_agot_input_flow_rate_last', '6_hours_ago_input_flow_rate_mean', 
    '6_hours_ago_reservoir_level_percentage_first', '6_hours_ago_reservoir_level_percentage_last', '6_hours_ago_reservoir_level_percentage_mean', 
    '6_hours_ago_output_flow_rate_first', '6_hours_ago_output_flow_rate_last', '6_hours_ago_output_flow_rate_mean', '6_hours_ago_pressure_first', 
    '6_hours_ago_pressure_last', '6_hours_ago_pressure_mean', '6_hours_agot_pump_1_duration_sum', '6_hours_agot_pump_2_duration_sum', '6_hours_ago_temperature', 
    '6_hours_ago_precipitation', '6_hours_ago_humidity', '12_hours_ago_input_flow_rate_first', '12_hours_agot_input_flow_rate_last', '12_hours_ago_input_flow_rate_mean', 
    '12_hours_ago_reservoir_level_percentage_first', '12_hours_ago_reservoir_level_percentage_last', '12_hours_ago_reservoir_level_percentage_mean', '12_hours_ago_output_flow_rate_first', 
    '12_hours_ago_output_flow_rate_last', '12_hours_ago_output_flow_rate_mean', '12_hours_ago_pressure_first', '12_hours_ago_pressure_last', '12_hours_ago_pressure_mean', 
    '12_hours_agot_pump_1_duration_sum', '12_hours_agot_pump_2_duration_sum', '12_hours_ago_temperature', '12_hours_ago_precipitation', '12_hours_ago_humidity', '24_hours_ago_input_flow_rate_first',
    '24_hours_agot_input_flow_rate_last', '24_hours_ago_input_flow_rate_mean', '24_hours_ago_reservoir_level_percentage_first', '24_hours_ago_reservoir_level_percentage_last', 
    '24_hours_ago_reservoir_level_percentage_mean', '24_hours_ago_output_flow_rate_first', '24_hours_ago_output_flow_rate_last', '24_hours_ago_output_flow_rate_mean', 
    '24_hours_ago_pressure_first', '24_hours_ago_pressure_last', '24_hours_ago_pressure_mean', '24_hours_agot_pump_1_duration_sum', '24_hours_agot_pump_2_duration_sum', 
    '24_hours_ago_temperature', '24_hours_ago_precipitation', '24_hours_ago_humidity', '26_hours_ago_input_flow_rate_first', '26_hours_agot_input_flow_rate_last', 
    '26_hours_ago_input_flow_rate_mean', '26_hours_ago_reservoir_level_percentage_first', '26_hours_ago_reservoir_level_percentage_last', '26_hours_ago_reservoir_level_percentage_mean', 
    '26_hours_ago_output_flow_rate_first', '26_hours_ago_output_flow_rate_last', '26_hours_ago_output_flow_rate_mean', '26_hours_ago_pressure_first', '26_hours_ago_pressure_last', 
    '26_hours_ago_pressure_mean', '26_hours_agot_pump_1_duration_sum', '26_hours_agot_pump_2_duration_sum', '26_hours_ago_temperature', '26_hours_ago_precipitation', 
    '26_hours_ago_humidity', '48_hours_ago_input_flow_rate_first', '48_hours_agot_input_flow_rate_last', '48_hours_ago_input_flow_rate_mean', 
    '48_hours_ago_reservoir_level_percentage_first', '48_hours_ago_reservoir_level_percentage_last', '48_hours_ago_reservoir_level_percentage_mean', 
    '48_hours_ago_output_flow_rate_first', '48_hours_ago_output_flow_rate_last', '48_hours_ago_output_flow_rate_mean', '48_hours_ago_pressure_first', 
    '48_hours_ago_pressure_last', '48_hours_ago_pressure_mean', '48_hours_agot_pump_1_duration_sum', '48_hours_agot_pump_2_duration_sum', '48_hours_ago_temperature', 
    '48_hours_ago_precipitation', '48_hours_ago_humidity', '72_hours_ago_input_flow_rate_first', '72_hours_agot_input_flow_rate_last', '72_hours_ago_input_flow_rate_mean', 
    '72_hours_ago_reservoir_level_percentage_first', '72_hours_ago_reservoir_level_percentage_last', '72_hours_ago_reservoir_level_percentage_mean', '72_hours_ago_output_flow_rate_first', 
    '72_hours_ago_output_flow_rate_last', '72_hours_ago_output_flow_rate_mean', '72_hours_ago_pressure_first', '72_hours_ago_pressure_last', '72_hours_ago_pressure_mean', 
    '72_hours_agot_pump_1_duration_sum', '72_hours_agot_pump_2_duration_sum', '72_hours_ago_temperature', '72_hours_ago_precipitation', '72_hours_ago_humidity', 
    '2_hours_rolling_input_flow_rate_diff', '2_hours_rolling_output_flow_rate_diff', '2_hours_rolling_reservoir_level_change', '2_hours_rolling_pressure_change', 
    '2_hours_rolling_change_from_last_hour_output_flow_rate_mean', '2_hours_rolling_temperature', '2_hours_rolling_precipitation', '2_hours_rolling_humidity', 
    '3_hours_rolling_input_flow_rate_diff', '3_hours_rolling_output_flow_rate_diff', '3_hours_rolling_reservoir_level_change', '3_hours_rolling_pressure_change', 
    '3_hours_rolling_change_from_last_hour_output_flow_rate_mean', '3_hours_rolling_temperature', '3_hours_rolling_precipitation', '3_hours_rolling_humidity', 
    '6_hours_rolling_input_flow_rate_diff', '6_hours_rolling_output_flow_rate_diff', '6_hours_rolling_reservoir_level_change', '6_hours_rolling_pressure_change', 
    '6_hours_rolling_change_from_last_hour_output_flow_rate_mean', '6_hours_rolling_temperature', '6_hours_rolling_precipitation', '6_hours_rolling_humidity', 
    '12_hours_rolling_input_flow_rate_diff', '12_hours_rolling_output_flow_rate_diff', '12_hours_rolling_reservoir_level_change', '12_hours_rolling_pressure_change', 
    '12_hours_rolling_change_from_last_hour_output_flow_rate_mean', '12_hours_rolling_temperature', '12_hours_rolling_precipitation', '12_hours_rolling_humidity', 
    '24_hours_rolling_input_flow_rate_diff', '24_hours_rolling_output_flow_rate_diff', '24_hours_rolling_reservoir_level_change', '24_hours_rolling_pressure_change', 
    '24_hours_rolling_change_from_last_hour_output_flow_rate_mean', '24_hours_rolling_temperature', '24_hours_rolling_precipitation', '24_hours_rolling_humidity', 
    '36_hours_rolling_input_flow_rate_diff', '36_hours_rolling_output_flow_rate_diff', '36_hours_rolling_reservoir_level_change', '36_hours_rolling_pressure_change', 
    '36_hours_rolling_change_from_last_hour_output_flow_rate_mean', '36_hours_rolling_temperature', '36_hours_rolling_precipitation', '36_hours_rolling_humidity', 
    '48_hours_rolling_input_flow_rate_diff', '48_hours_rolling_output_flow_rate_diff', '48_hours_rolling_reservoir_level_change', '48_hours_rolling_pressure_change', 
    '48_hours_rolling_change_from_last_hour_output_flow_rate_mean', '48_hours_rolling_temperature', '48_hours_rolling_precipitation', '48_hours_rolling_humidity', 
    '72_hours_rolling_input_flow_rate_diff', '72_hours_rolling_output_flow_rate_diff', '72_hours_rolling_reservoir_level_change', '72_hours_rolling_pressure_change', 
    '72_hours_rolling_change_from_last_hour_output_flow_rate_mean', '72_hours_rolling_temperature', '72_hours_rolling_precipitation', '72_hours_rolling_humidity', 'inputed_row']

all_non_weather_features = [
    'hour', 'day_of_week', 'week_of_year', 'year', '1_hours_ago_input_flow_rate_first', '1_hours_agot_input_flow_rate_last', '1_hours_ago_input_flow_rate_mean', 
    '1_hours_ago_reservoir_level_percentage_first', '1_hours_ago_reservoir_level_percentage_last', '1_hours_ago_reservoir_level_percentage_mean', '1_hours_ago_output_flow_rate_first', 
    '1_hours_ago_output_flow_rate_last', '1_hours_ago_output_flow_rate_mean', '1_hours_ago_pressure_first', '1_hours_ago_pressure_last', '1_hours_ago_pressure_mean', 
    '1_hours_agot_pump_1_duration_sum', '1_hours_agot_pump_2_duration_sum', '2_hours_ago_input_flow_rate_first', '2_hours_agot_input_flow_rate_last', '2_hours_ago_input_flow_rate_mean', 
    '2_hours_ago_reservoir_level_percentage_first', '2_hours_ago_reservoir_level_percentage_last', '2_hours_ago_reservoir_level_percentage_mean', '2_hours_ago_output_flow_rate_first', 
    '2_hours_ago_output_flow_rate_last', '2_hours_ago_output_flow_rate_mean', '2_hours_ago_pressure_first', '2_hours_ago_pressure_last', '2_hours_ago_pressure_mean', 
    '2_hours_agot_pump_1_duration_sum', '2_hours_agot_pump_2_duration_sum', '3_hours_ago_input_flow_rate_first', '3_hours_agot_input_flow_rate_last', '3_hours_ago_input_flow_rate_mean', 
    '3_hours_ago_reservoir_level_percentage_first', '3_hours_ago_reservoir_level_percentage_last', '3_hours_ago_reservoir_level_percentage_mean', '3_hours_ago_output_flow_rate_first', 
    '3_hours_ago_output_flow_rate_last', '3_hours_ago_output_flow_rate_mean', '3_hours_ago_pressure_first', '3_hours_ago_pressure_last', '3_hours_ago_pressure_mean', 
    '3_hours_agot_pump_1_duration_sum', '3_hours_agot_pump_2_duration_sum', '6_hours_ago_input_flow_rate_first', '6_hours_agot_input_flow_rate_last', '6_hours_ago_input_flow_rate_mean', 
    '6_hours_ago_reservoir_level_percentage_first', '6_hours_ago_reservoir_level_percentage_last', '6_hours_ago_reservoir_level_percentage_mean', '6_hours_ago_output_flow_rate_first', 
    '6_hours_ago_output_flow_rate_last', '6_hours_ago_output_flow_rate_mean', '6_hours_ago_pressure_first', '6_hours_ago_pressure_last', '6_hours_ago_pressure_mean', 
    '6_hours_agot_pump_1_duration_sum', '6_hours_agot_pump_2_duration_sum', '12_hours_ago_input_flow_rate_first', '12_hours_agot_input_flow_rate_last', '12_hours_ago_input_flow_rate_mean', 
    '12_hours_ago_reservoir_level_percentage_first', '12_hours_ago_reservoir_level_percentage_last', '12_hours_ago_reservoir_level_percentage_mean', '12_hours_ago_output_flow_rate_first', 
    '12_hours_ago_output_flow_rate_last', '12_hours_ago_output_flow_rate_mean', '12_hours_ago_pressure_first', '12_hours_ago_pressure_last', '12_hours_ago_pressure_mean', 
    '12_hours_agot_pump_1_duration_sum', '12_hours_agot_pump_2_duration_sum', '24_hours_ago_input_flow_rate_first', '24_hours_agot_input_flow_rate_last', '24_hours_ago_input_flow_rate_mean', 
    '24_hours_ago_reservoir_level_percentage_first', '24_hours_ago_reservoir_level_percentage_last', '24_hours_ago_reservoir_level_percentage_mean', '24_hours_ago_output_flow_rate_first', 
    '24_hours_ago_output_flow_rate_last', '24_hours_ago_output_flow_rate_mean', '24_hours_ago_pressure_first', '24_hours_ago_pressure_last', '24_hours_ago_pressure_mean', 
    '24_hours_agot_pump_1_duration_sum', '24_hours_agot_pump_2_duration_sum', '26_hours_ago_input_flow_rate_first', '26_hours_agot_input_flow_rate_last', '26_hours_ago_input_flow_rate_mean', 
    '26_hours_ago_reservoir_level_percentage_first', '26_hours_ago_reservoir_level_percentage_last', '26_hours_ago_reservoir_level_percentage_mean', '26_hours_ago_output_flow_rate_first', 
    '26_hours_ago_output_flow_rate_last', '26_hours_ago_output_flow_rate_mean', '26_hours_ago_pressure_first', '26_hours_ago_pressure_last', '26_hours_ago_pressure_mean', 
    '26_hours_agot_pump_1_duration_sum', '26_hours_agot_pump_2_duration_sum', '48_hours_ago_input_flow_rate_first', '48_hours_agot_input_flow_rate_last', '48_hours_ago_input_flow_rate_mean', 
    '48_hours_ago_reservoir_level_percentage_first', '48_hours_ago_reservoir_level_percentage_last', '48_hours_ago_reservoir_level_percentage_mean', '48_hours_ago_output_flow_rate_first', 
    '48_hours_ago_output_flow_rate_last', '48_hours_ago_output_flow_rate_mean', '48_hours_ago_pressure_first', '48_hours_ago_pressure_last', '48_hours_ago_pressure_mean', 
    '48_hours_agot_pump_1_duration_sum', '48_hours_agot_pump_2_duration_sum', '72_hours_ago_input_flow_rate_first', '72_hours_agot_input_flow_rate_last', '72_hours_ago_input_flow_rate_mean', 
    '72_hours_ago_reservoir_level_percentage_first', '72_hours_ago_reservoir_level_percentage_last', '72_hours_ago_reservoir_level_percentage_mean', '72_hours_ago_output_flow_rate_first', 
    '72_hours_ago_output_flow_rate_last', '72_hours_ago_output_flow_rate_mean', '72_hours_ago_pressure_first', '72_hours_ago_pressure_last', '72_hours_ago_pressure_mean', 
    '72_hours_agot_pump_1_duration_sum', '72_hours_agot_pump_2_duration_sum', '2_hours_rolling_input_flow_rate_diff', '2_hours_rolling_output_flow_rate_diff', 
    '2_hours_rolling_reservoir_level_change', '2_hours_rolling_pressure_change', '2_hours_rolling_change_from_last_hour_output_flow_rate_mean', '3_hours_rolling_input_flow_rate_diff', 
    '3_hours_rolling_output_flow_rate_diff', '3_hours_rolling_reservoir_level_change', '3_hours_rolling_pressure_change', '3_hours_rolling_change_from_last_hour_output_flow_rate_mean', 
    '6_hours_rolling_input_flow_rate_diff', '6_hours_rolling_output_flow_rate_diff', '6_hours_rolling_reservoir_level_change', '6_hours_rolling_pressure_change', 
    '6_hours_rolling_change_from_last_hour_output_flow_rate_mean', '12_hours_rolling_input_flow_rate_diff', '12_hours_rolling_output_flow_rate_diff', '12_hours_rolling_reservoir_level_change', 
    '12_hours_rolling_pressure_change', '12_hours_rolling_change_from_last_hour_output_flow_rate_mean', '24_hours_rolling_input_flow_rate_diff', '24_hours_rolling_output_flow_rate_diff', 
    '24_hours_rolling_reservoir_level_change', '24_hours_rolling_pressure_change', '24_hours_rolling_change_from_last_hour_output_flow_rate_mean', '36_hours_rolling_input_flow_rate_diff', 
    '36_hours_rolling_output_flow_rate_diff', '36_hours_rolling_reservoir_level_change', '36_hours_rolling_pressure_change', '36_hours_rolling_change_from_last_hour_output_flow_rate_mean', 
    '48_hours_rolling_input_flow_rate_diff', '48_hours_rolling_output_flow_rate_diff', '48_hours_rolling_reservoir_level_change', '48_hours_rolling_pressure_change', 
    '48_hours_rolling_change_from_last_hour_output_flow_rate_mean', '72_hours_rolling_input_flow_rate_diff', '72_hours_rolling_output_flow_rate_diff', '72_hours_rolling_reservoir_level_change', 
    '72_hours_rolling_pressure_change', '72_hours_rolling_change_from_last_hour_output_flow_rate_mean', 'inputed_row']
